apiVersion: v1
kind: Service
metadata:
  name: crypto-ingestion
spec:
  selector:
    app: crypto-ingestor
    type: ClusterIp
  ports:
    - port: 80
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-ingestor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-ingestor
  template:
    metadata:
      labels:
        app: crypto-ingestor
    spec:
      containers:
      - name: crypto-ingestor
        image: testimage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
