apiVersion: v1
kind: Service
metadata:
  name: crypto-ingestion
spec:
  selector:
    app: crypto-ingestor
    type: ClusterIP
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-ingestor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-ingestor
  template:
    metadata:
      labels:
        app: crypto-ingestor
    spec:
      containers:
      - name: crypto-ingestor
        image: 074047115132.dkr.ecr.ap-southeast-2.amazonaws.com/processor-repository:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: "250m"
