name: ci-ingestion

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: build & deploy image
    runs-on: ubuntu-latest
    outputs:
      IMAGE_URI: ${{ steps.push.outputs.IMAGE_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.3'
        id: install
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.ACCESSKEYID}}
          aws-secret-access-key: ${{secrets.SECRETACCESSKEY}}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag and push image to ECR
        id: push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ingestion-repository
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
          docker push $REGISTRY/$REPOSITORY:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ingestion_cluster-cluster --region ap-southeast-2

      - name: testss
        run: |
          echo("${aws sts get-caller-identity}")

      - name: Deploy to EKS
        if: steps.push.outcome == 'success'
        run: |
          kubectl apply -f k8s/eks-auth.yaml
          kubectl apply -f k8s/deployment.yaml
